<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-JB166E2" failures="2" tests="6" name="Surefire test" time="43.991" errors="0" timestamp="2025-04-29T21:40:42 IDT">
  <testcase classname="DeleteItemTest" name="testDeleteObjectAndVerifyInaccessible" time="4.379">
    <failure type="java.lang.AssertionError" message="gcloud delete command failed expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: gcloud delete command failed expected [0] but found [1]
at DeleteItemTest.testDeleteObjectAndVerifyInaccessible(DeleteItemTest.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteObjectAndVerifyInaccessible -->
  <testcase classname="ObjectListTests" name="TestPrivateObjectExisitsAndNotLoad" time="12.936"/>
  <testcase classname="ObjectListTests" name="testPublicObjectExistsAndLoadsInBrowser" time="2.444">
    <failure type="java.lang.AssertionError" message="Public file did not load successfully expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: Public file did not load successfully expected [200] but found [403]
at ObjectListTests.testPublicObjectExistsAndLoadsInBrowser(ObjectListTests.java:81)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testPublicObjectExistsAndLoadsInBrowser -->
  <testcase classname="SignedUrlTests" name="generateSignedUrlTest" time="2.053"/>
  <testcase classname="SignedUrlTests" name="verifyAccessToSignedUrlTest" time="11.748"/>
  <testcase classname="UpdateAccessTests" name="testUpdateAccessPublicToPrivate" time="10.392"/>
</testsuite> <!-- Surefire test -->
